2025-04-20 15:58:30,777 - INFO - 程序啟動
2025-04-20 15:58:30,789 - INFO - 檢測可用的音訊輸入設備：
2025-04-20 15:58:30,790 - INFO - 輸入設備 ID 0 - 你的小妖精上線啦 Microphone
2025-04-20 15:58:30,790 - INFO - 輸入設備 ID 1 - MacBook Air Microphone
2025-04-20 15:58:30,791 - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2025-04-20 15:58:30,792 - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2025-04-20 15:58:30,793 - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2025-04-20 15:58:30,794 - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2025-04-20 15:58:30,795 - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2025-04-20 15:58:30,795 - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2025-04-20 15:58:30,796 - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2025-04-20 15:58:30,798 - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2025-04-20 15:58:30,798 - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2025-04-20 15:58:30,798 - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2025-04-20 15:58:30,798 - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2025-04-20 15:58:30,801 - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: env
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: assume-role
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: assume-role-with-web-identity
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: sso
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: shared-credentials-file
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: custom-process
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: config-file
2025-04-20 15:58:30,807 - DEBUG - Looking for credentials via: ec2-credentials-file
2025-04-20 15:58:30,808 - DEBUG - Looking for credentials via: boto-config
2025-04-20 15:58:30,808 - DEBUG - Looking for credentials via: container-role
2025-04-20 15:58:30,808 - DEBUG - Looking for credentials via: iam-role
2025-04-20 15:58:30,809 - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2025-04-20 15:58:31,834 - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
           ^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x10d7bbfd0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/utils.py", line 459, in _fetch_metadata_token
    response = self._session.send(request.prepare())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/httpsession.py", line 499, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2025-04-20 15:58:31,846 - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2025-04-20 15:58:32,849 - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/iam/security-credentials/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
Traceback (most recent call last):
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/awsrequest.py", line 96, in request
    rval = super().request(method, url, body, headers, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/awsrequest.py", line 123, in _send_output
    self.send(msg)
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/awsrequest.py", line 223, in send
    return super().send(str)
           ^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x10e174ad0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/utils.py", line 514, in _get_request
    response = self._session.send(request.prepare())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yun/anaconda3/lib/python3.11/site-packages/botocore/httpsession.py", line 499, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/iam/security-credentials/"
2025-04-20 15:58:32,854 - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2025-04-20 15:58:32,856 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/endpoints.json
2025-04-20 15:58:32,877 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sdk-default-configuration.json
2025-04-20 15:58:32,877 - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x106fd53a0>
2025-04-20 15:58:32,927 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sts/2011-06-15/service-2.json.gz
2025-04-20 15:58:32,940 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sts/2011-06-15/endpoint-rule-set-1.json.gz
2025-04-20 15:58:32,941 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/partitions.json
2025-04-20 15:58:32,941 - DEBUG - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x106f116c0>
2025-04-20 15:58:32,941 - DEBUG - Looking for endpoint for sts via: environment_service
2025-04-20 15:58:32,941 - DEBUG - Looking for endpoint for sts via: environment_global
2025-04-20 15:58:32,941 - DEBUG - Looking for endpoint for sts via: config_service
2025-04-20 15:58:32,941 - DEBUG - Looking for endpoint for sts via: config_global
2025-04-20 15:58:32,941 - DEBUG - No configured endpoint found.
2025-04-20 15:58:32,983 - DEBUG - Setting sts timeout as (60, 60)
2025-04-20 15:58:32,986 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/_retry.json
2025-04-20 15:58:32,987 - DEBUG - Registering retry handlers for service: sts
2025-04-20 15:58:32,988 - DEBUG - Event before-parameter-build.sts.GetCallerIdentity: calling handler <function generate_idempotent_uuid at 0x106fd6ca0>
2025-04-20 15:58:32,988 - DEBUG - Calling endpoint provider with parameters: {'Region': 'aws-global', 'UseDualStack': False, 'UseFIPS': False, 'UseGlobalEndpoint': True}
2025-04-20 15:58:32,988 - DEBUG - Endpoint provider result: https://sts.amazonaws.com
2025-04-20 15:58:32,988 - DEBUG - Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2025-04-20 15:58:32,989 - DEBUG - Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 'sts'}
2025-04-20 15:58:32,989 - DEBUG - Event before-call.sts.GetCallerIdentity: calling handler <function add_recursion_detection_header at 0x106fd5c60>
2025-04-20 15:58:32,989 - DEBUG - Event before-call.sts.GetCallerIdentity: calling handler <function inject_api_version_header_if_needed at 0x106ff87c0>
2025-04-20 15:58:32,989 - DEBUG - Making request for OperationModel(name=GetCallerIdentity) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'Boto3/1.29.2 md/Botocore#1.32.7 md/awscrt#0.16.26 ua/2.0 os/macos#24.3.0 md/arch#arm64 lang/python#3.11.4 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.32.7'}, 'body': {'Action': 'GetCallerIdentity', 'Version': '2011-06-15'}, 'url': 'https://sts.amazonaws.com/', 'context': {'client_region': 'aws-global', 'client_config': <botocore.config.Config object at 0x10e761f90>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 'sts'}}}
2025-04-20 15:58:32,989 - DEBUG - Event request-created.sts.GetCallerIdentity: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10e761f50>>
2025-04-20 15:58:32,989 - DEBUG - Event choose-signer.sts.GetCallerIdentity: calling handler <function set_operation_specific_signer at 0x106fd6b60>
2025-04-20 15:58:32,990 - ERROR - AWS 憑證錯誤: Unable to locate credentials
2025-04-20 16:08:31,986 - INFO - 程序啟動
2025-04-20 16:08:31,996 - INFO - 檢測可用的音訊輸入設備：
2025-04-20 16:08:31,996 - INFO - 輸入設備 ID 0 - 你的小妖精上線啦 Microphone
2025-04-20 16:08:31,996 - INFO - 輸入設備 ID 1 - MacBook Air Microphone
2025-04-20 16:08:31,997 - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2025-04-20 16:08:31,998 - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2025-04-20 16:08:31,998 - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2025-04-20 16:08:31,999 - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2025-04-20 16:08:31,999 - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2025-04-20 16:08:31,999 - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2025-04-20 16:08:31,999 - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2025-04-20 16:08:32,001 - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2025-04-20 16:08:32,001 - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2025-04-20 16:08:32,002 - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2025-04-20 16:08:32,002 - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2025-04-20 16:08:32,005 - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2025-04-20 16:08:32,020 - DEBUG - Looking for credentials via: env
2025-04-20 16:08:32,020 - DEBUG - Looking for credentials via: assume-role
2025-04-20 16:08:32,020 - DEBUG - Looking for credentials via: assume-role-with-web-identity
2025-04-20 16:08:32,020 - DEBUG - Looking for credentials via: sso
2025-04-20 16:08:32,020 - DEBUG - Looking for credentials via: shared-credentials-file
2025-04-20 16:08:32,021 - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2025-04-20 16:08:32,023 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/endpoints.json
2025-04-20 16:08:32,043 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sdk-default-configuration.json
2025-04-20 16:08:32,043 - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x102b993a0>
2025-04-20 16:08:32,082 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sts/2011-06-15/service-2.json.gz
2025-04-20 16:08:32,096 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sts/2011-06-15/endpoint-rule-set-1.json.gz
2025-04-20 16:08:32,096 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/partitions.json
2025-04-20 16:08:32,097 - DEBUG - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x102ad56c0>
2025-04-20 16:08:32,097 - DEBUG - Looking for endpoint for sts via: environment_service
2025-04-20 16:08:32,097 - DEBUG - Looking for endpoint for sts via: environment_global
2025-04-20 16:08:32,097 - DEBUG - Looking for endpoint for sts via: config_service
2025-04-20 16:08:32,097 - DEBUG - Looking for endpoint for sts via: config_global
2025-04-20 16:08:32,097 - DEBUG - No configured endpoint found.
2025-04-20 16:08:32,163 - DEBUG - Setting sts timeout as (60, 60)
2025-04-20 16:08:32,166 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/_retry.json
2025-04-20 16:08:32,166 - DEBUG - Registering retry handlers for service: sts
2025-04-20 16:08:32,166 - DEBUG - Event before-parameter-build.sts.GetCallerIdentity: calling handler <function generate_idempotent_uuid at 0x102b9aca0>
2025-04-20 16:08:32,167 - DEBUG - Calling endpoint provider with parameters: {'Region': 'us-east-2', 'UseDualStack': False, 'UseFIPS': False, 'UseGlobalEndpoint': True}
2025-04-20 16:08:32,167 - DEBUG - Endpoint provider result: https://sts.amazonaws.com
2025-04-20 16:08:32,167 - DEBUG - Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2025-04-20 16:08:32,167 - DEBUG - Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 'sts'}
2025-04-20 16:08:32,167 - DEBUG - Event before-call.sts.GetCallerIdentity: calling handler <function add_recursion_detection_header at 0x102b99c60>
2025-04-20 16:08:32,167 - DEBUG - Event before-call.sts.GetCallerIdentity: calling handler <function inject_api_version_header_if_needed at 0x102bbc7c0>
2025-04-20 16:08:32,167 - DEBUG - Making request for OperationModel(name=GetCallerIdentity) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'Boto3/1.29.2 md/Botocore#1.32.7 md/awscrt#0.16.26 ua/2.0 os/macos#24.3.0 md/arch#arm64 lang/python#3.11.4 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.32.7'}, 'body': {'Action': 'GetCallerIdentity', 'Version': '2011-06-15'}, 'url': 'https://sts.amazonaws.com/', 'context': {'client_region': 'us-east-2', 'client_config': <botocore.config.Config object at 0x10a19ffd0>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 'sts'}}}
2025-04-20 16:08:32,167 - DEBUG - Event request-created.sts.GetCallerIdentity: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10a19ff90>>
2025-04-20 16:08:32,167 - DEBUG - Event choose-signer.sts.GetCallerIdentity: calling handler <function set_operation_specific_signer at 0x102b9ab60>
2025-04-20 16:08:32,169 - DEBUG - Event request-created.sts.GetCallerIdentity: calling handler <function add_retry_headers at 0x102bbcf40>
2025-04-20 16:08:32,169 - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://sts.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'Boto3/1.29.2 md/Botocore#1.32.7 md/awscrt#0.16.26 ua/2.0 os/macos#24.3.0 md/arch#arm64 lang/python#3.11.4 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.32.7', 'host': b'sts.amazonaws.com', 'X-Amz-Date': b'20250420T080832Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=AKIA4JXS5ZEADYJ6IMMO/20250420/us-east-1/sts/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=0bdf132ba2ca1ab0c42cdccc5256648eb14578d6f788d39764f1464aa4ee750a', 'amz-sdk-invocation-id': b'0c0a5fdb-b8cf-465f-9701-d037ee32b1f1', 'amz-sdk-request': b'attempt=1', 'Content-Length': '43'}>
2025-04-20 16:08:32,172 - DEBUG - Certificate path: /Users/yun/anaconda3/lib/python3.11/site-packages/certifi/cacert.pem
2025-04-20 16:08:32,173 - DEBUG - Starting new HTTPS connection (1): sts.amazonaws.com:443
2025-04-20 16:08:33,005 - DEBUG - https://sts.amazonaws.com:443 "POST / HTTP/1.1" 200 402
2025-04-20 16:08:33,005 - DEBUG - Response headers: {'x-amzn-RequestId': '0fd44337-e385-4fb2-8019-2afbe846f2b3', 'Content-Type': 'text/xml', 'Content-Length': '402', 'Date': 'Sun, 20 Apr 2025 08:08:24 GMT'}
2025-04-20 16:08:33,005 - DEBUG - Response body:
b'<GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">\n  <GetCallerIdentityResult>\n    <Arn>arn:aws:iam::845544278272:user/voice</Arn>\n    <UserId>AIDA4JXS5ZEABPHLMG4IT</UserId>\n    <Account>845544278272</Account>\n  </GetCallerIdentityResult>\n  <ResponseMetadata>\n    <RequestId>0fd44337-e385-4fb2-8019-2afbe846f2b3</RequestId>\n  </ResponseMetadata>\n</GetCallerIdentityResponse>\n'
2025-04-20 16:08:33,006 - DEBUG - Event needs-retry.sts.GetCallerIdentity: calling handler <botocore.retryhandler.RetryHandler object at 0x10a1bd450>
2025-04-20 16:08:33,006 - DEBUG - No retry needed.
2025-04-20 16:08:33,006 - INFO - AWS 帳號驗證成功: 845544278272
2025-04-20 16:08:33,007 - INFO - 使用模型: amazon.titan-text-express-v1
2025-04-20 16:08:33,007 - INFO - AWS 區域: us-east-1
2025-04-20 16:08:33,008 - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x102b993a0>
2025-04-20 16:08:33,008 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/bedrock-runtime/2023-09-30/service-2.json.gz
2025-04-20 16:08:33,009 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/bedrock-runtime/2023-09-30/endpoint-rule-set-1.json.gz
2025-04-20 16:08:33,009 - DEBUG - Event creating-client-class.bedrock-runtime: calling handler <function add_generate_presigned_url at 0x102ad56c0>
2025-04-20 16:08:33,009 - DEBUG - Looking for endpoint for bedrock-runtime via: environment_service
2025-04-20 16:08:33,009 - DEBUG - Looking for endpoint for bedrock-runtime via: environment_global
2025-04-20 16:08:33,009 - DEBUG - Looking for endpoint for bedrock-runtime via: config_service
2025-04-20 16:08:33,009 - DEBUG - Looking for endpoint for bedrock-runtime via: config_global
2025-04-20 16:08:33,009 - DEBUG - No configured endpoint found.
2025-04-20 16:08:33,010 - DEBUG - Creating a regex based endpoint for bedrock-runtime, us-east-1
2025-04-20 16:08:33,044 - DEBUG - Setting bedrock-runtime timeout as (60, 60)
2025-04-20 16:08:33,044 - DEBUG - Registering retry handlers for service: bedrock-runtime
2025-04-20 16:08:33,045 - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x102b993a0>
2025-04-20 16:08:33,045 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/polly/2016-06-10/service-2.json.gz
2025-04-20 16:08:33,046 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/polly/2016-06-10/endpoint-rule-set-1.json.gz
2025-04-20 16:08:33,047 - DEBUG - Event creating-client-class.polly: calling handler <function add_generate_presigned_url at 0x102ad56c0>
2025-04-20 16:08:33,047 - DEBUG - Looking for endpoint for polly via: environment_service
2025-04-20 16:08:33,047 - DEBUG - Looking for endpoint for polly via: environment_global
2025-04-20 16:08:33,047 - DEBUG - Looking for endpoint for polly via: config_service
2025-04-20 16:08:33,047 - DEBUG - Looking for endpoint for polly via: config_global
2025-04-20 16:08:33,047 - DEBUG - No configured endpoint found.
2025-04-20 16:08:33,069 - DEBUG - Setting polly timeout as (60, 60)
2025-04-20 16:08:33,070 - DEBUG - Registering retry handlers for service: polly
2025-04-20 16:08:33,071 - INFO - 開始主程序執行
2025-04-20 16:08:33,186 - INFO - 音訊設備初始化成功
2025-04-20 16:08:33,186 - DEBUG - Using selector: KqueueSelector
2025-04-20 16:08:33,186 - INFO - 開始語音轉錄服務
2025-04-20 16:08:34,541 - ERROR - 轉錄服務錯誤: 1 validation error detected: Value 'cmn-CN' at 'languageCode' failed to satisfy constraint: Member must satisfy enum value set: [en-IE, ar-AE, zh-TW, zh-HK, en-US, uk-UA, en-AB, en-IN, ar-SA, zh-CN, eu-ES, en-ZA, tl-PH, so-SO, sk-SK, ru-RU, ro-RO, lv-LV, id-ID, hr-HR, fi-FI, pl-PL, no-NO, nl-NL, pt-PT, es-ES, th-TH, de-DE, it-IT, fr-FR, sr-RS, af-ZA, en-NZ, ko-KR, el-GR, de-CH, hi-IN, vi-VN, ms-MY, he-IL, cs-CZ, gl-ES, da-DK, en-AU, zu-ZA, en-WL, pt-BR, fa-IR, sv-SE, ja-JP, ca-ES, es-US, fr-CA, en-GB]
2025-04-20 16:09:19,326 - INFO - 程序啟動
2025-04-20 16:09:19,335 - INFO - 檢測可用的音訊輸入設備：
2025-04-20 16:09:19,335 - INFO - 輸入設備 ID 0 - 你的小妖精上線啦 Microphone
2025-04-20 16:09:19,335 - INFO - 輸入設備 ID 1 - MacBook Air Microphone
2025-04-20 16:09:19,335 - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2025-04-20 16:09:19,336 - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2025-04-20 16:09:19,337 - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2025-04-20 16:09:19,337 - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2025-04-20 16:09:19,337 - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2025-04-20 16:09:19,338 - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2025-04-20 16:09:19,338 - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2025-04-20 16:09:19,340 - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2025-04-20 16:09:19,340 - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2025-04-20 16:09:19,340 - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2025-04-20 16:09:19,340 - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2025-04-20 16:09:19,352 - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2025-04-20 16:09:19,361 - DEBUG - Looking for credentials via: env
2025-04-20 16:09:19,361 - DEBUG - Looking for credentials via: assume-role
2025-04-20 16:09:19,361 - DEBUG - Looking for credentials via: assume-role-with-web-identity
2025-04-20 16:09:19,361 - DEBUG - Looking for credentials via: sso
2025-04-20 16:09:19,361 - DEBUG - Looking for credentials via: shared-credentials-file
2025-04-20 16:09:19,361 - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2025-04-20 16:09:19,362 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/endpoints.json
2025-04-20 16:09:19,387 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sdk-default-configuration.json
2025-04-20 16:09:19,387 - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x1046793a0>
2025-04-20 16:09:19,423 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sts/2011-06-15/service-2.json.gz
2025-04-20 16:09:19,444 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/sts/2011-06-15/endpoint-rule-set-1.json.gz
2025-04-20 16:09:19,445 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/partitions.json
2025-04-20 16:09:19,445 - DEBUG - Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x1045b56c0>
2025-04-20 16:09:19,445 - DEBUG - Looking for endpoint for sts via: environment_service
2025-04-20 16:09:19,446 - DEBUG - Looking for endpoint for sts via: environment_global
2025-04-20 16:09:19,446 - DEBUG - Looking for endpoint for sts via: config_service
2025-04-20 16:09:19,446 - DEBUG - Looking for endpoint for sts via: config_global
2025-04-20 16:09:19,446 - DEBUG - No configured endpoint found.
2025-04-20 16:09:19,451 - DEBUG - Setting sts timeout as (60, 60)
2025-04-20 16:09:19,452 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/_retry.json
2025-04-20 16:09:19,453 - DEBUG - Registering retry handlers for service: sts
2025-04-20 16:09:19,453 - DEBUG - Event before-parameter-build.sts.GetCallerIdentity: calling handler <function generate_idempotent_uuid at 0x10467aca0>
2025-04-20 16:09:19,453 - DEBUG - Calling endpoint provider with parameters: {'Region': 'us-east-2', 'UseDualStack': False, 'UseFIPS': False, 'UseGlobalEndpoint': True}
2025-04-20 16:09:19,454 - DEBUG - Endpoint provider result: https://sts.amazonaws.com
2025-04-20 16:09:19,454 - DEBUG - Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2025-04-20 16:09:19,454 - DEBUG - Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 'sts'}
2025-04-20 16:09:19,455 - DEBUG - Event before-call.sts.GetCallerIdentity: calling handler <function add_recursion_detection_header at 0x104679c60>
2025-04-20 16:09:19,455 - DEBUG - Event before-call.sts.GetCallerIdentity: calling handler <function inject_api_version_header_if_needed at 0x10469c7c0>
2025-04-20 16:09:19,455 - DEBUG - Making request for OperationModel(name=GetCallerIdentity) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'Boto3/1.29.2 md/Botocore#1.32.7 md/awscrt#0.16.26 ua/2.0 os/macos#24.3.0 md/arch#arm64 lang/python#3.11.4 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.32.7'}, 'body': {'Action': 'GetCallerIdentity', 'Version': '2011-06-15'}, 'url': 'https://sts.amazonaws.com/', 'context': {'client_region': 'us-east-2', 'client_config': <botocore.config.Config object at 0x10b060a10>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 'sts'}}}
2025-04-20 16:09:19,455 - DEBUG - Event request-created.sts.GetCallerIdentity: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x11bf30650>>
2025-04-20 16:09:19,455 - DEBUG - Event choose-signer.sts.GetCallerIdentity: calling handler <function set_operation_specific_signer at 0x10467ab60>
2025-04-20 16:09:19,457 - DEBUG - Event request-created.sts.GetCallerIdentity: calling handler <function add_retry_headers at 0x10469cf40>
2025-04-20 16:09:19,457 - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=https://sts.amazonaws.com/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'Boto3/1.29.2 md/Botocore#1.32.7 md/awscrt#0.16.26 ua/2.0 os/macos#24.3.0 md/arch#arm64 lang/python#3.11.4 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.32.7', 'host': b'sts.amazonaws.com', 'X-Amz-Date': b'20250420T080919Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=AKIA4JXS5ZEADYJ6IMMO/20250420/us-east-1/sts/aws4_request, SignedHeaders=content-type;host;x-amz-date, Signature=5bfa47525a5e4adb73071db43007430ee9d80ed1e9dd1ed32c8b0f9a8b58a81e', 'amz-sdk-invocation-id': b'9c08e3c7-6560-45b9-9cce-c32ff19788ea', 'amz-sdk-request': b'attempt=1', 'Content-Length': '43'}>
2025-04-20 16:09:19,460 - DEBUG - Certificate path: /Users/yun/anaconda3/lib/python3.11/site-packages/certifi/cacert.pem
2025-04-20 16:09:19,460 - DEBUG - Starting new HTTPS connection (1): sts.amazonaws.com:443
2025-04-20 16:09:20,270 - DEBUG - https://sts.amazonaws.com:443 "POST / HTTP/1.1" 200 402
2025-04-20 16:09:20,270 - DEBUG - Response headers: {'x-amzn-RequestId': '63525db0-827d-4aa5-918c-d55d022a377e', 'Content-Type': 'text/xml', 'Content-Length': '402', 'Date': 'Sun, 20 Apr 2025 08:09:11 GMT'}
2025-04-20 16:09:20,270 - DEBUG - Response body:
b'<GetCallerIdentityResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">\n  <GetCallerIdentityResult>\n    <Arn>arn:aws:iam::845544278272:user/voice</Arn>\n    <UserId>AIDA4JXS5ZEABPHLMG4IT</UserId>\n    <Account>845544278272</Account>\n  </GetCallerIdentityResult>\n  <ResponseMetadata>\n    <RequestId>63525db0-827d-4aa5-918c-d55d022a377e</RequestId>\n  </ResponseMetadata>\n</GetCallerIdentityResponse>\n'
2025-04-20 16:09:20,271 - DEBUG - Event needs-retry.sts.GetCallerIdentity: calling handler <botocore.retryhandler.RetryHandler object at 0x11bf45a50>
2025-04-20 16:09:20,271 - DEBUG - No retry needed.
2025-04-20 16:09:20,271 - INFO - AWS 帳號驗證成功: 845544278272
2025-04-20 16:09:20,273 - INFO - 使用模型: amazon.titan-text-express-v1
2025-04-20 16:09:20,273 - INFO - AWS 區域: us-east-1
2025-04-20 16:09:20,273 - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x1046793a0>
2025-04-20 16:09:20,274 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/bedrock-runtime/2023-09-30/service-2.json.gz
2025-04-20 16:09:20,275 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/bedrock-runtime/2023-09-30/endpoint-rule-set-1.json.gz
2025-04-20 16:09:20,275 - DEBUG - Event creating-client-class.bedrock-runtime: calling handler <function add_generate_presigned_url at 0x1045b56c0>
2025-04-20 16:09:20,275 - DEBUG - Looking for endpoint for bedrock-runtime via: environment_service
2025-04-20 16:09:20,275 - DEBUG - Looking for endpoint for bedrock-runtime via: environment_global
2025-04-20 16:09:20,275 - DEBUG - Looking for endpoint for bedrock-runtime via: config_service
2025-04-20 16:09:20,276 - DEBUG - Looking for endpoint for bedrock-runtime via: config_global
2025-04-20 16:09:20,276 - DEBUG - No configured endpoint found.
2025-04-20 16:09:20,276 - DEBUG - Creating a regex based endpoint for bedrock-runtime, us-east-1
2025-04-20 16:09:20,280 - DEBUG - Setting bedrock-runtime timeout as (60, 60)
2025-04-20 16:09:20,281 - DEBUG - Registering retry handlers for service: bedrock-runtime
2025-04-20 16:09:20,282 - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x1046793a0>
2025-04-20 16:09:20,283 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/polly/2016-06-10/service-2.json.gz
2025-04-20 16:09:20,284 - DEBUG - Loading JSON file: /Users/yun/anaconda3/lib/python3.11/site-packages/botocore/data/polly/2016-06-10/endpoint-rule-set-1.json.gz
2025-04-20 16:09:20,285 - DEBUG - Event creating-client-class.polly: calling handler <function add_generate_presigned_url at 0x1045b56c0>
2025-04-20 16:09:20,285 - DEBUG - Looking for endpoint for polly via: environment_service
2025-04-20 16:09:20,285 - DEBUG - Looking for endpoint for polly via: environment_global
2025-04-20 16:09:20,285 - DEBUG - Looking for endpoint for polly via: config_service
2025-04-20 16:09:20,285 - DEBUG - Looking for endpoint for polly via: config_global
2025-04-20 16:09:20,285 - DEBUG - No configured endpoint found.
2025-04-20 16:09:20,287 - DEBUG - Setting polly timeout as (60, 60)
2025-04-20 16:09:20,288 - DEBUG - Registering retry handlers for service: polly
2025-04-20 16:09:20,290 - INFO - 開始主程序執行
2025-04-20 16:09:20,409 - INFO - 音訊設備初始化成功
2025-04-20 16:09:20,409 - DEBUG - Using selector: KqueueSelector
2025-04-20 16:09:20,410 - INFO - 開始語音轉錄服務
2025-04-20 16:09:21,787 - INFO - Transcribe 串流已啟動
2025-04-20 16:09:21,787 - DEBUG - 初始化 BedrockWrapper
2025-04-20 16:09:21,787 - ERROR - 轉錄服務錯誤: TranscriptResultStreamHandler.__init__() takes 2 positional arguments but 3 were given
